# Test pipline
# Testing agent pools on US_ING cluster


trigger:
- none

pool:
  name: US_ING

steps:
- script: echo "Local agent works!"
  displayName: 'Testing agent'

- script: |
    echo "Hostname : ${hostname}"
  displayName: 'Agent info'
